name: CI/CD Pipeline

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract tag version
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            VERSION=${{ env.TAG }}
          push: true
          tags: |
            ${{ vars.DOCKER_HUB_USERNAME }}/hello-world:${{ env.TAG }}
            ${{ vars.DOCKER_HUB_USERNAME }}/hello-world:latest

  pull-and-deploy:
    name: Pull and Deploy to Setonix
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PAWSEY_SSH_KEY }}

      - name: Add Setonix to known hosts
        run: ssh-keyscan setonix.pawsey.org.au >> ~/.ssh/known_hosts

      - name: Execute remote deployment
        run: |
          ssh -Y ksmith1@setonix.pawsey.org.au 'bash -s' < make_modulefile.sh /software/projects/askaprt/ksmith1 docker://ksmith21/hello-world ${{ env.TAG }}
