name: CI/CD Pipeline

on:
  release:
    types: [published]

env:
  TAG: ${{ github.ref_name }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            VERSION=${{ env.TAG }}
          push: true
          tags: |
            ${{ vars.DOCKER_HUB_USERNAME }}/hello-world:${{ env.TAG }}
            ${{ vars.DOCKER_HUB_USERNAME }}/hello-world:latest

  pull-and-deploy:
    name: Pull and Deploy to Setonix
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Install SSH key
      #   uses: webfactory/ssh-agent@v0.8.0
      #   with:
      #     ssh-private-key: ${{ secrets.PAWSEY_SSH_KEY }}

      - name: Set up SSH
        run: |
          # command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )
          # eval $(ssh-agent -s)
          # echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          # chmod 400 ~/.ssh/id_rsa
          # ssh-add ~/.ssh/id_rsa
          # chmod 700 ~/.ssh
          # ssh-keyscan setonix.pawsey.org.au >> ~/.ssh/known_hosts
          mkdir -p ~/.ssh
          echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Setonix to known hosts
        run: ssh-keyscan setonix.pawsey.org.au >> ~/.ssh/known_hosts

      - name: Execute remote deployment
        run: |
          ssh -Y ksmith1@setonix.pawsey.org.au 'bash -s' < make_modulefile.sh /software/projects/askaprt/ksmith1 docker://ksmith21/hello-world ${{ env.TAG }}
